version: '3'

services:
  sreality_crawler:
    build: .
    volumes:
      - ./sreality_crawler:/app/sreality_crawler
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=flats
      - DB_USER=postgres
      - DB_PASS=postgres
    command: ["scrapy", "crawl", "sreality"]

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=flats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres